schema_version = "1.0.0"

id = "dtmimporter"
version = "0.3.0"
name = "HiRISE DTM Importer"
tagline = "Import a HiRISE DTM as a mesh"
maintainer = "Nicholas Wolf (nicwolf@pirl.lpl.arizona.edu)"
type = "add-on"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
category = "Import-Export"

[permissions]
files = "Read DTM .img files from disk"
